apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dp
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: BOT_TOKEN
            - name: GETGEOAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: GETGEOAPI_KEY
            - name: REDIS_BASE_URL
              value: "{{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL
        - name: {{ .Release.Name }}-celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["celery"]
          args: ["-A", "core", "worker", "-l", "info", "-P", "prefork", "-c", "2", "-E", "-B"]
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: BOT_TOKEN
            - name: GETGEOAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: GETGEOAPI_KEY
            - name: REDIS_BASE_URL
              value: "{{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL
