apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  BOT_TOKEN: {{ .Values.env.botToken | b64enc }}
  GETGEOAPI_KEY: {{ default "None" .Values.env.getGeoApiKey | b64enc }}
  DATABASE_URL: {{ .Values.env.databaseUrl | b64enc }}