apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
      app: redis
      chart: redis-{{ .Chart.Version }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: {{ .Release.Name }}-redis
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.9-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-redis