apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bot
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bot
    spec:
      containers:
        - name: {{ .Release.Name }}-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: BOT_TOKEN
            - name: REDIS_BASE_URL
              value: "redis://{{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-celery
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-celery
    spec:
      containers:
        - name: {{ .Release.Name }}-celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["celery"]
          args: ["-A", "core", "worker", "-l", "info", "-P", "prefork", "-c", "2", "-E", "-B"]
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: BOT_TOKEN
            - name: REDIS_BASE_URL
              value: "redis://{{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - core
                - inspect
                - ping
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - core
                - inspect
                - ping
            timeoutSeconds: 5
---